#!/bin/sh

POSTGRES_PORT=5434
POSTGRES_DB=photodb
POSTGRES_PASS=test123 
POSTGRES_URL=postgres://admin:test123@bear:5434/photodb
export POSTGRES_PORT POSTGRES_DB POSTGRES_PASS POSTGRES_URL
BITGARTEN_SERVER=http://bear:8181/fotos
BITGARTEN_USERNAME=admin
BITGARTEN_PASSWORD=test123
BITGARTEN_LOCATION=photodb
export BITGARTEN_SERVER BITGARTEN_USERNAME BITGARTEN_PASSWORD BITGARTEN_LOCATION
LOGPATH=`pwd`/logs
#ENABLE_DEBUG=1
#export ENABLE_DEBUG LOGPATH
export LOGPATH

bin/darwin_arm64/picloadql -A $* 2>&1|tee piclql.out

