#!/bin/bash

CURDIR=`pwd`
echo $CURDIR

LOGPATH=$CURDIR/logs
if [ ! -d ${LOGPATH} ]; then
  mkdir ${LOGPATH}
fi
export LOGPATH

POSTGRES_URL=postgres://admin:test123@bear:5434/photodb
export POSTGRES_PORT POSTGRES_DB POSTGRES_PASS POSTGRES_URL
BITGARTEN_SERVER=http://bear:8181/fotos
BITGARTEN_USERNAME=admin
BITGARTEN_PASSWORD=test123
BITGARTEN_LOCATION=photodb
export BITGARTEN_SERVER BITGARTEN_USERNAME BITGARTEN_PASSWORD BITGARTEN_LOCATION

