// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// BrowseList implements browseList operation.
//
// Retrieves a list of Browseable locations.
//
// GET /rest/file/browse
func (UnimplementedHandler) BrowseList(ctx context.Context) (r BrowseListRes, _ error) {
	return r, ht.ErrNotImplemented
}

// BrowseLocation implements browseLocation operation.
//
// Retrieves a list of files in the defined location.
//
// GET /rest/file/browse/{path}
func (UnimplementedHandler) BrowseLocation(ctx context.Context, params BrowseLocationParams) (r BrowseLocationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateDirectory implements createDirectory operation.
//
// Create a new directory.
//
// PUT /rest/file/{path}
func (UnimplementedHandler) CreateDirectory(ctx context.Context, params CreateDirectoryParams) (r CreateDirectoryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteFileLocation implements deleteFileLocation operation.
//
// Delete the file on the given location.
//
// DELETE /rest/file/{path}
func (UnimplementedHandler) DeleteFileLocation(ctx context.Context, params DeleteFileLocationParams) (r DeleteFileLocationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DownloadFile implements downloadFile operation.
//
// Download a file out of file location.
//
// GET /rest/file/{path}
func (UnimplementedHandler) DownloadFile(ctx context.Context, params DownloadFileParams) (r DownloadFileRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetLoginSession implements getLoginSession operation.
//
// Login receiving JWT.
//
// GET /login
func (UnimplementedHandler) GetLoginSession(ctx context.Context) (r GetLoginSessionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// LoginSession implements loginSession operation.
//
// Login receiving JWT.
//
// PUT /login
func (UnimplementedHandler) LoginSession(ctx context.Context) (r LoginSessionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// LogoutSessionCompat implements logoutSessionCompat operation.
//
// Logout the session.
//
// PUT /logout
func (UnimplementedHandler) LogoutSessionCompat(ctx context.Context) (r LogoutSessionCompatRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PushLoginSession implements pushLoginSession operation.
//
// Login receiving JWT.
//
// POST /login
func (UnimplementedHandler) PushLoginSession(ctx context.Context) (r PushLoginSessionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveSessionCompat implements removeSessionCompat operation.
//
// Remove the session.
//
// GET /logoff
func (UnimplementedHandler) RemoveSessionCompat(ctx context.Context) (r RemoveSessionCompatRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UploadFile implements uploadFile operation.
//
// Upload a new file to the given location.
//
// POST /rest/file/{path}
func (UnimplementedHandler) UploadFile(ctx context.Context, req *UploadFileReq, params UploadFileParams) (r UploadFileRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
