// Code generated by ogen, DO NOT EDIT.
package api

type BrowseListRes interface {
	browseListRes()
}

type BrowseLocationRes interface {
	browseLocationRes()
}

type CreateDirectoryRes interface {
	createDirectoryRes()
}

type DeleteFileLocationRes interface {
	deleteFileLocationRes()
}

type DownloadFileRes interface {
	downloadFileRes()
}

type GetLoginSessionRes interface {
	getLoginSessionRes()
}

type LoginSessionRes interface {
	loginSessionRes()
}

type LogoutSessionCompatRes interface {
	logoutSessionCompatRes()
}

type PushLoginSessionRes interface {
	pushLoginSessionRes()
}

type RemoveSessionCompatRes interface {
	removeSessionCompatRes()
}

type UploadFileRes interface {
	uploadFileRes()
}
