// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
	"io"
	"time"

	"github.com/google/uuid"

	ht "github.com/ogen-go/ogen/http"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/AuthorizationToken
type AuthorizationToken struct {
	Token     OptString `json:"token"`
	AdminRole OptBool   `json:"AdminRole"`
	User      OptUser   `json:"User"`
}

// GetToken returns the value of Token.
func (s *AuthorizationToken) GetToken() OptString {
	return s.Token
}

// GetAdminRole returns the value of AdminRole.
func (s *AuthorizationToken) GetAdminRole() OptBool {
	return s.AdminRole
}

// GetUser returns the value of User.
func (s *AuthorizationToken) GetUser() OptUser {
	return s.User
}

// SetToken sets the value of Token.
func (s *AuthorizationToken) SetToken(val OptString) {
	s.Token = val
}

// SetAdminRole sets the value of AdminRole.
func (s *AuthorizationToken) SetAdminRole(val OptBool) {
	s.AdminRole = val
}

// SetUser sets the value of User.
func (s *AuthorizationToken) SetUser(val OptUser) {
	s.User = val
}

// AuthorizationTokenHeaders wraps AuthorizationToken with response headers.
type AuthorizationTokenHeaders struct {
	XToken   OptString
	Response AuthorizationToken
}

// GetXToken returns the value of XToken.
func (s *AuthorizationTokenHeaders) GetXToken() OptString {
	return s.XToken
}

// GetResponse returns the value of Response.
func (s *AuthorizationTokenHeaders) GetResponse() AuthorizationToken {
	return s.Response
}

// SetXToken sets the value of XToken.
func (s *AuthorizationTokenHeaders) SetXToken(val OptString) {
	s.XToken = val
}

// SetResponse sets the value of Response.
func (s *AuthorizationTokenHeaders) SetResponse(val AuthorizationToken) {
	s.Response = val
}

func (*AuthorizationTokenHeaders) getLoginSessionRes()  {}
func (*AuthorizationTokenHeaders) loginSessionRes()     {}
func (*AuthorizationTokenHeaders) pushLoginSessionRes() {}

type BasicAuth struct {
	Username string
	Password string
}

// GetUsername returns the value of Username.
func (s *BasicAuth) GetUsername() string {
	return s.Username
}

// GetPassword returns the value of Password.
func (s *BasicAuth) GetPassword() string {
	return s.Password
}

// SetUsername sets the value of Username.
func (s *BasicAuth) SetUsername(val string) {
	s.Username = val
}

// SetPassword sets the value of Password.
func (s *BasicAuth) SetPassword(val string) {
	s.Password = val
}

type BearerAuth struct {
	Token string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

type BrowseListBadRequest Error

func (*BrowseListBadRequest) browseListRes() {}

// BrowseListForbidden is response for BrowseList operation.
type BrowseListForbidden struct{}

func (*BrowseListForbidden) browseListRes() {}

type BrowseListNotFound Error

func (*BrowseListNotFound) browseListRes() {}

// BrowseListUnauthorized is response for BrowseList operation.
type BrowseListUnauthorized struct{}

func (*BrowseListUnauthorized) browseListRes() {}

type BrowseLocationBadRequest Error

func (*BrowseLocationBadRequest) browseLocationRes() {}

// BrowseLocationForbidden is response for BrowseLocation operation.
type BrowseLocationForbidden struct{}

func (*BrowseLocationForbidden) browseLocationRes() {}

type BrowseLocationNotFound Error

func (*BrowseLocationNotFound) browseLocationRes() {}

// BrowseLocationOK represents sum type.
type BrowseLocationOK struct {
	Type           BrowseLocationOKType // switch on this field
	DirectoryFiles DirectoryFiles
	File           File
}

// BrowseLocationOKType is oneOf type of BrowseLocationOK.
type BrowseLocationOKType string

// Possible values for BrowseLocationOKType.
const (
	DirectoryFilesBrowseLocationOK BrowseLocationOKType = "DirectoryFiles"
	FileBrowseLocationOK           BrowseLocationOKType = "File"
)

// IsDirectoryFiles reports whether BrowseLocationOK is DirectoryFiles.
func (s BrowseLocationOK) IsDirectoryFiles() bool { return s.Type == DirectoryFilesBrowseLocationOK }

// IsFile reports whether BrowseLocationOK is File.
func (s BrowseLocationOK) IsFile() bool { return s.Type == FileBrowseLocationOK }

// SetDirectoryFiles sets BrowseLocationOK to DirectoryFiles.
func (s *BrowseLocationOK) SetDirectoryFiles(v DirectoryFiles) {
	s.Type = DirectoryFilesBrowseLocationOK
	s.DirectoryFiles = v
}

// GetDirectoryFiles returns DirectoryFiles and true boolean if BrowseLocationOK is DirectoryFiles.
func (s BrowseLocationOK) GetDirectoryFiles() (v DirectoryFiles, ok bool) {
	if !s.IsDirectoryFiles() {
		return v, false
	}
	return s.DirectoryFiles, true
}

// NewDirectoryFilesBrowseLocationOK returns new BrowseLocationOK from DirectoryFiles.
func NewDirectoryFilesBrowseLocationOK(v DirectoryFiles) BrowseLocationOK {
	var s BrowseLocationOK
	s.SetDirectoryFiles(v)
	return s
}

// SetFile sets BrowseLocationOK to File.
func (s *BrowseLocationOK) SetFile(v File) {
	s.Type = FileBrowseLocationOK
	s.File = v
}

// GetFile returns File and true boolean if BrowseLocationOK is File.
func (s BrowseLocationOK) GetFile() (v File, ok bool) {
	if !s.IsFile() {
		return v, false
	}
	return s.File, true
}

// NewFileBrowseLocationOK returns new BrowseLocationOK from File.
func NewFileBrowseLocationOK(v File) BrowseLocationOK {
	var s BrowseLocationOK
	s.SetFile(v)
	return s
}

func (*BrowseLocationOK) browseLocationRes() {}

// BrowseLocationUnauthorized is response for BrowseLocation operation.
type BrowseLocationUnauthorized struct{}

func (*BrowseLocationUnauthorized) browseLocationRes() {}

type CreateDirectoryBadRequest Error

func (*CreateDirectoryBadRequest) createDirectoryRes() {}

// CreateDirectoryForbidden is response for CreateDirectory operation.
type CreateDirectoryForbidden struct{}

func (*CreateDirectoryForbidden) createDirectoryRes() {}

type CreateDirectoryNotFound Error

func (*CreateDirectoryNotFound) createDirectoryRes() {}

// CreateDirectoryUnauthorized is response for CreateDirectory operation.
type CreateDirectoryUnauthorized struct{}

func (*CreateDirectoryUnauthorized) createDirectoryRes() {}

type DeleteFileLocationBadRequest Error

func (*DeleteFileLocationBadRequest) deleteFileLocationRes() {}

// DeleteFileLocationForbidden is response for DeleteFileLocation operation.
type DeleteFileLocationForbidden struct{}

func (*DeleteFileLocationForbidden) deleteFileLocationRes() {}

type DeleteFileLocationNotFound Error

func (*DeleteFileLocationNotFound) deleteFileLocationRes() {}

// DeleteFileLocationUnauthorized is response for DeleteFileLocation operation.
type DeleteFileLocationUnauthorized struct{}

func (*DeleteFileLocationUnauthorized) deleteFileLocationRes() {}

// Ref: #/components/schemas/Directories
type Directories struct {
	Directories []Directory `json:"Directories"`
	System      OptString   `json:"system"`
}

// GetDirectories returns the value of Directories.
func (s *Directories) GetDirectories() []Directory {
	return s.Directories
}

// GetSystem returns the value of System.
func (s *Directories) GetSystem() OptString {
	return s.System
}

// SetDirectories sets the value of Directories.
func (s *Directories) SetDirectories(val []Directory) {
	s.Directories = val
}

// SetSystem sets the value of System.
func (s *Directories) SetSystem(val OptString) {
	s.System = val
}

func (*Directories) browseListRes() {}

// Ref: #/components/schemas/Directory
type Directory struct {
	Location OptString `json:"Location"`
	Name     OptString `json:"Name"`
}

// GetLocation returns the value of Location.
func (s *Directory) GetLocation() OptString {
	return s.Location
}

// GetName returns the value of Name.
func (s *Directory) GetName() OptString {
	return s.Name
}

// SetLocation sets the value of Location.
func (s *Directory) SetLocation(val OptString) {
	s.Location = val
}

// SetName sets the value of Name.
func (s *Directory) SetName(val OptString) {
	s.Name = val
}

// Ref: #/components/schemas/DirectoryFiles
type DirectoryFiles struct {
	Location OptString `json:"Location"`
	Path     OptString `json:"Path"`
	Files    []File    `json:"Files"`
	System   OptString `json:"system"`
}

// GetLocation returns the value of Location.
func (s *DirectoryFiles) GetLocation() OptString {
	return s.Location
}

// GetPath returns the value of Path.
func (s *DirectoryFiles) GetPath() OptString {
	return s.Path
}

// GetFiles returns the value of Files.
func (s *DirectoryFiles) GetFiles() []File {
	return s.Files
}

// GetSystem returns the value of System.
func (s *DirectoryFiles) GetSystem() OptString {
	return s.System
}

// SetLocation sets the value of Location.
func (s *DirectoryFiles) SetLocation(val OptString) {
	s.Location = val
}

// SetPath sets the value of Path.
func (s *DirectoryFiles) SetPath(val OptString) {
	s.Path = val
}

// SetFiles sets the value of Files.
func (s *DirectoryFiles) SetFiles(val []File) {
	s.Files = val
}

// SetSystem sets the value of System.
func (s *DirectoryFiles) SetSystem(val OptString) {
	s.System = val
}

type DownloadFileBadRequest Error

func (*DownloadFileBadRequest) downloadFileRes() {}

// DownloadFileForbidden is response for DownloadFile operation.
type DownloadFileForbidden struct{}

func (*DownloadFileForbidden) downloadFileRes() {}

type DownloadFileNotFound Error

func (*DownloadFileNotFound) downloadFileRes() {}

type DownloadFileOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s DownloadFileOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*DownloadFileOK) downloadFileRes() {}

// DownloadFileUnauthorized is response for DownloadFile operation.
type DownloadFileUnauthorized struct{}

func (*DownloadFileUnauthorized) downloadFileRes() {}

// Ref: #/components/schemas/Error
type Error struct {
	Code    OptString     `json:"code"`
	Message OptString     `json:"message"`
	Target  OptString     `json:"target"`
	Error   OptErrorError `json:"Error"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() OptString {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() OptString {
	return s.Message
}

// GetTarget returns the value of Target.
func (s *Error) GetTarget() OptString {
	return s.Target
}

// GetError returns the value of Error.
func (s *Error) GetError() OptErrorError {
	return s.Error
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val OptString) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val OptString) {
	s.Message = val
}

// SetTarget sets the value of Target.
func (s *Error) SetTarget(val OptString) {
	s.Target = val
}

// SetError sets the value of Error.
func (s *Error) SetError(val OptErrorError) {
	s.Error = val
}

func (*Error) getLoginSessionRes()  {}
func (*Error) loginSessionRes()     {}
func (*Error) pushLoginSessionRes() {}

type ErrorError struct {
	Code    OptString `json:"code"`
	Message OptString `json:"message"`
	Target  OptString `json:"target"`
}

// GetCode returns the value of Code.
func (s *ErrorError) GetCode() OptString {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ErrorError) GetMessage() OptString {
	return s.Message
}

// GetTarget returns the value of Target.
func (s *ErrorError) GetTarget() OptString {
	return s.Target
}

// SetCode sets the value of Code.
func (s *ErrorError) SetCode(val OptString) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ErrorError) SetMessage(val OptString) {
	s.Message = val
}

// SetTarget sets the value of Target.
func (s *ErrorError) SetTarget(val OptString) {
	s.Target = val
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// Ref: #/components/schemas/File
type File struct {
	Name     OptString   `json:"Name"`
	Type     OptString   `json:"Type"`
	Modified OptDateTime `json:"Modified"`
	Size     OptInt64    `json:"Size"`
}

// GetName returns the value of Name.
func (s *File) GetName() OptString {
	return s.Name
}

// GetType returns the value of Type.
func (s *File) GetType() OptString {
	return s.Type
}

// GetModified returns the value of Modified.
func (s *File) GetModified() OptDateTime {
	return s.Modified
}

// GetSize returns the value of Size.
func (s *File) GetSize() OptInt64 {
	return s.Size
}

// SetName sets the value of Name.
func (s *File) SetName(val OptString) {
	s.Name = val
}

// SetType sets the value of Type.
func (s *File) SetType(val OptString) {
	s.Type = val
}

// SetModified sets the value of Modified.
func (s *File) SetModified(val OptDateTime) {
	s.Modified = val
}

// SetSize sets the value of Size.
func (s *File) SetSize(val OptInt64) {
	s.Size = val
}

// GetLoginSessionForbidden is response for GetLoginSession operation.
type GetLoginSessionForbidden struct{}

func (*GetLoginSessionForbidden) getLoginSessionRes() {}

// GetLoginSessionUnauthorized is response for GetLoginSession operation.
type GetLoginSessionUnauthorized struct{}

func (*GetLoginSessionUnauthorized) getLoginSessionRes() {}

// LoginSessionForbidden is response for LoginSession operation.
type LoginSessionForbidden struct{}

func (*LoginSessionForbidden) loginSessionRes() {}

// LoginSessionUnauthorized is response for LoginSession operation.
type LoginSessionUnauthorized struct{}

func (*LoginSessionUnauthorized) loginSessionRes() {}

type LogoutSessionCompatBadRequest Error

func (*LogoutSessionCompatBadRequest) logoutSessionCompatRes() {}

type LogoutSessionCompatNotFound Error

func (*LogoutSessionCompatNotFound) logoutSessionCompatRes() {}

// LogoutSessionCompatOK is response for LogoutSessionCompat operation.
type LogoutSessionCompatOK struct{}

func (*LogoutSessionCompatOK) logoutSessionCompatRes() {}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptErrorError returns new OptErrorError with value set to v.
func NewOptErrorError(v ErrorError) OptErrorError {
	return OptErrorError{
		Value: v,
		Set:   true,
	}
}

// OptErrorError is optional ErrorError.
type OptErrorError struct {
	Value ErrorError
	Set   bool
}

// IsSet returns true if OptErrorError was set.
func (o OptErrorError) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptErrorError) Reset() {
	var v ErrorError
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptErrorError) SetTo(v ErrorError) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptErrorError) Get() (v ErrorError, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptErrorError) Or(d ErrorError) ErrorError {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptFloat64 returns new OptFloat64 with value set to v.
func NewOptFloat64(v float64) OptFloat64 {
	return OptFloat64{
		Value: v,
		Set:   true,
	}
}

// OptFloat64 is optional float64.
type OptFloat64 struct {
	Value float64
	Set   bool
}

// IsSet returns true if OptFloat64 was set.
func (o OptFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat64) SetTo(v float64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat64) Get() (v float64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptStatusResponseStatus returns new OptStatusResponseStatus with value set to v.
func NewOptStatusResponseStatus(v StatusResponseStatus) OptStatusResponseStatus {
	return OptStatusResponseStatus{
		Value: v,
		Set:   true,
	}
}

// OptStatusResponseStatus is optional StatusResponseStatus.
type OptStatusResponseStatus struct {
	Value StatusResponseStatus
	Set   bool
}

// IsSet returns true if OptStatusResponseStatus was set.
func (o OptStatusResponseStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptStatusResponseStatus) Reset() {
	var v StatusResponseStatus
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptStatusResponseStatus) SetTo(v StatusResponseStatus) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptStatusResponseStatus) Get() (v StatusResponseStatus, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptStatusResponseStatus) Or(d StatusResponseStatus) StatusResponseStatus {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v uuid.UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional uuid.UUID.
type OptUUID struct {
	Value uuid.UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v uuid.UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUser returns new OptUser with value set to v.
func NewOptUser(v User) OptUser {
	return OptUser{
		Value: v,
		Set:   true,
	}
}

// OptUser is optional User.
type OptUser struct {
	Value User
	Set   bool
}

// IsSet returns true if OptUser was set.
func (o OptUser) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUser) Reset() {
	var v User
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUser) SetTo(v User) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUser) Get() (v User, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUser) Or(d User) User {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// PushLoginSessionForbidden is response for PushLoginSession operation.
type PushLoginSessionForbidden struct{}

func (*PushLoginSessionForbidden) pushLoginSessionRes() {}

// PushLoginSessionUnauthorized is response for PushLoginSession operation.
type PushLoginSessionUnauthorized struct{}

func (*PushLoginSessionUnauthorized) pushLoginSessionRes() {}

type RemoveSessionCompatBadRequest Error

func (*RemoveSessionCompatBadRequest) removeSessionCompatRes() {}

type RemoveSessionCompatNotFound Error

func (*RemoveSessionCompatNotFound) removeSessionCompatRes() {}

// RemoveSessionCompatOK is response for RemoveSessionCompat operation.
type RemoveSessionCompatOK struct{}

func (*RemoveSessionCompatOK) removeSessionCompatRes() {}

// Ref: #/components/schemas/StatusResponse
type StatusResponse struct {
	Status OptStatusResponseStatus `json:"Status"`
}

// GetStatus returns the value of Status.
func (s *StatusResponse) GetStatus() OptStatusResponseStatus {
	return s.Status
}

// SetStatus sets the value of Status.
func (s *StatusResponse) SetStatus(val OptStatusResponseStatus) {
	s.Status = val
}

func (*StatusResponse) createDirectoryRes()    {}
func (*StatusResponse) deleteFileLocationRes() {}
func (*StatusResponse) uploadFileRes()         {}

type StatusResponseStatus struct {
	Action  OptString  `json:"Action"`
	Code    OptString  `json:"Code"`
	Dbid    OptFloat64 `json:"Dbid"`
	Target  OptString  `json:"Target"`
	Message OptString  `json:"Message"`
}

// GetAction returns the value of Action.
func (s *StatusResponseStatus) GetAction() OptString {
	return s.Action
}

// GetCode returns the value of Code.
func (s *StatusResponseStatus) GetCode() OptString {
	return s.Code
}

// GetDbid returns the value of Dbid.
func (s *StatusResponseStatus) GetDbid() OptFloat64 {
	return s.Dbid
}

// GetTarget returns the value of Target.
func (s *StatusResponseStatus) GetTarget() OptString {
	return s.Target
}

// GetMessage returns the value of Message.
func (s *StatusResponseStatus) GetMessage() OptString {
	return s.Message
}

// SetAction sets the value of Action.
func (s *StatusResponseStatus) SetAction(val OptString) {
	s.Action = val
}

// SetCode sets the value of Code.
func (s *StatusResponseStatus) SetCode(val OptString) {
	s.Code = val
}

// SetDbid sets the value of Dbid.
func (s *StatusResponseStatus) SetDbid(val OptFloat64) {
	s.Dbid = val
}

// SetTarget sets the value of Target.
func (s *StatusResponseStatus) SetTarget(val OptString) {
	s.Target = val
}

// SetMessage sets the value of Message.
func (s *StatusResponseStatus) SetMessage(val OptString) {
	s.Message = val
}

type TokenCheck struct {
	APIKey string
}

// GetAPIKey returns the value of APIKey.
func (s *TokenCheck) GetAPIKey() string {
	return s.APIKey
}

// SetAPIKey sets the value of APIKey.
func (s *TokenCheck) SetAPIKey(val string) {
	s.APIKey = val
}

type UploadFileBadRequest Error

func (*UploadFileBadRequest) uploadFileRes() {}

// UploadFileForbidden is response for UploadFile operation.
type UploadFileForbidden struct{}

func (*UploadFileForbidden) uploadFileRes() {}

type UploadFileNotFound Error

func (*UploadFileNotFound) uploadFileRes() {}

type UploadFileOKTextPlain struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s UploadFileOKTextPlain) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*UploadFileOKTextPlain) uploadFileRes() {}

type UploadFileReq struct {
	// Upload file.
	UploadFile ht.MultipartFile `json:"uploadFile"`
}

// GetUploadFile returns the value of UploadFile.
func (s *UploadFileReq) GetUploadFile() ht.MultipartFile {
	return s.UploadFile
}

// SetUploadFile sets the value of UploadFile.
func (s *UploadFileReq) SetUploadFile(val ht.MultipartFile) {
	s.UploadFile = val
}

// UploadFileUnauthorized is response for UploadFile operation.
type UploadFileUnauthorized struct{}

func (*UploadFileUnauthorized) uploadFileRes() {}

// Ref: #/components/schemas/User
type User struct {
	Email      OptString   `json:"email"`
	Name       OptString   `json:"name"`
	Picture    OptString   `json:"Picture"`
	LongName   OptString   `json:"LongName"`
	UUID       OptUUID     `json:"UUID"`
	LastLogin  OptDateTime `json:"LastLogin"`
	Created    OptDateTime `json:"Created"`
	Permission OptString   `json:"Permission"`
}

// GetEmail returns the value of Email.
func (s *User) GetEmail() OptString {
	return s.Email
}

// GetName returns the value of Name.
func (s *User) GetName() OptString {
	return s.Name
}

// GetPicture returns the value of Picture.
func (s *User) GetPicture() OptString {
	return s.Picture
}

// GetLongName returns the value of LongName.
func (s *User) GetLongName() OptString {
	return s.LongName
}

// GetUUID returns the value of UUID.
func (s *User) GetUUID() OptUUID {
	return s.UUID
}

// GetLastLogin returns the value of LastLogin.
func (s *User) GetLastLogin() OptDateTime {
	return s.LastLogin
}

// GetCreated returns the value of Created.
func (s *User) GetCreated() OptDateTime {
	return s.Created
}

// GetPermission returns the value of Permission.
func (s *User) GetPermission() OptString {
	return s.Permission
}

// SetEmail sets the value of Email.
func (s *User) SetEmail(val OptString) {
	s.Email = val
}

// SetName sets the value of Name.
func (s *User) SetName(val OptString) {
	s.Name = val
}

// SetPicture sets the value of Picture.
func (s *User) SetPicture(val OptString) {
	s.Picture = val
}

// SetLongName sets the value of LongName.
func (s *User) SetLongName(val OptString) {
	s.LongName = val
}

// SetUUID sets the value of UUID.
func (s *User) SetUUID(val OptUUID) {
	s.UUID = val
}

// SetLastLogin sets the value of LastLogin.
func (s *User) SetLastLogin(val OptDateTime) {
	s.LastLogin = val
}

// SetCreated sets the value of Created.
func (s *User) SetCreated(val OptDateTime) {
	s.Created = val
}

// SetPermission sets the value of Permission.
func (s *User) SetPermission(val OptString) {
	s.Permission = val
}
